water_level = 0
default_stack_max = 1000
drop_item = false

# covered by playerphysics
movement_speed_crouch = 7
movement_speed_walk = 7
movement_speed_climb = 5
movement_liquid_sink = 20
movement_acceleration_default = 20
movement_acceleration_air = 1
movement_speed_fast = 100.0
movement_acceleration_fast = 1000.0
movement_speed_jump = 13
movement_gravity = 13.5

time_speed = 0
world_start_time = 5600

mgflat_spflags = nolakes,nohills,nocaverns
mg_flags = nocaves,nodungeons,light,decorations,biomes,ores
max_block_generate_distance = 1
# more than one thread causes mapgen to break
num_emerge_threads = 1